### ISSUE TITLE
The asymptotic running time of this algorithm is significantly slower than imperative implementations

### ISSUE THREAD

**Issue by joedaniels29** [tpoulsen/quicksort#1]
While attempting to choose a sorting routine for my many Elixir projects, (I have a lot of jumbled up lists that really need some order) I've stumbled upon this implementation of quick sort, and I've noticed that this implementation suffers the same issue with which the standard Haskell implementation is afflicted. 

http://stackoverflow.com/questions/7717691/why-is-the-minimalist-example-haskell-quicksort-not-a-true-quicksort

😄

**Comment by tpoulsen** [comment]
True, but for its use as an example, it's so elegant. 

May your lists be sorted quickly and efficiently!

Closing as wontfix 😉
